# Generated by Django 2.2 on 2021-12-27 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20211227_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survery',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity', verbose_name='Actividad'),
        ),
    ]
